  services:

    # --- REVERSE PROXY ---
    npm:
      image: 'jc21/nginx-proxy-manager:latest'
      container_name: npm
      restart: unless-stopped
      ports:
        - '80:80'     
        - '443:443'   
        - '81:81'     
      volumes:
        - ./config/npm/data:/data
        - ./config/npm/letsencrypt:/etc/letsencrypt
      networks:
        edge_net:
          ipv4_address: 10.0.0.10
        dns_cloudflare_net:
          ipv4_address: 10.10.0.10
        apps_net:
          ipv4_address: 10.20.0.10

    # --- ADGUARD HOME ---
    adguardhome:
      image: adguard/adguardhome:latest
      container_name: adguardhome
      restart: unless-stopped
      ports:
        - "53:53/tcp"
        - "53:53/udp"
        # Descomentar las siguientes líneas SOLO la primera vez para ejecutar el asistente inicial e ingresar a la interfaz web de AdGuard Home y añadir filtro *.home apuntando a la ip fija del server. Luego comentar nuevamente para evitar tener abiertos puertos innecesarios.:
        #- "3000:3000/tcp"
        #- "8080:80/tcp"
      volumes:
        - ./config/adguard/work:/opt/adguardhome/work
        - ./config/adguard/conf:/opt/adguardhome/conf
      networks:
        dns_cloudflare_net:
          ipv4_address: 10.10.0.20

    # --- CLOUDFLARE TUNNEL ---
    cloudflared:
      image: cloudflare/cloudflared:latest
      container_name: cloudflared
      restart: unless-stopped
      profiles:
        - external_access
      command: tunnel --no-autoupdate run
      environment:
        TUNNEL_TOKEN: ${CLOUDFLARE_TUNNEL_TOKEN}
      networks:
        dns_cloudflare_net:
          ipv4_address: 10.10.0.30

    # --- PORTAINER ---
    portainer:
      image: portainer/portainer-ce:latest
      container_name: portainer
      restart: unless-stopped
      security_opt:
        - no-new-privileges:true
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock:ro
        - ./config/portainer:/data
      networks:
        apps_net:
          ipv4_address: 10.20.0.20

    # --- DOZZLE ---
    dozzle:
      image: amir20/dozzle:latest
      container_name: dozzle
      restart: unless-stopped
      security_opt:
        - no-new-privileges:true
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock:ro
      networks:
        apps_net:
          ipv4_address: 10.20.0.30

    # --- NEXTCLOUD ---
    nextcloud:
      image: nextcloud:apache
      container_name: nextcloud
      restart: unless-stopped
      volumes:
        - ./config/nextcloud/html:/var/www/html
        - ./storage/users/nextcloud_data:/var/www/html/data
      environment:
        TZ: ${TZ}
        MYSQL_HOST: 10.40.0.20       
        MYSQL_DATABASE: nextcloud
        MYSQL_USER: nextcloud
        MYSQL_PASSWORD: ${NEXTCLOUD_DB_PASSWORD}
        NEXTCLOUD_ADMIN_USER: ${NEXTCLOUD_ADMIN_USER}
        NEXTCLOUD_ADMIN_PASSWORD: ${NEXTCLOUD_ADMIN_PASSWORD}
        NEXTCLOUD_TRUSTED_DOMAINS: cloud.home ${SERVER_IP}
      networks:
        apps_net:
          ipv4_address: 10.20.0.40
        nextcloud_db_net:          
          ipv4_address: 10.40.0.10
    
    # --- JELLYFIN MEDIA SERVER ---
    jellyfin:
      image: jellyfin/jellyfin:latest
      container_name: jellyfin
      restart: unless-stopped
      volumes:
        - ./config/jellyfin:/config
        - ./config/jellyfin_cache:/cache
        - ./storage/media:/media:ro
      environment:
        TZ: ${TZ}
      networks:
        apps_net:
          ipv4_address: 10.20.0.50

    # --- SAMBA (NAS) ---
    samba:
      image: dperson/samba:latest
      container_name: samba
      restart: unless-stopped
      ports:
        - "139:139"
        - "445:445"
      volumes:
        - ./storage/public:/storage/public
        - ./storage/media:/storage/media
        - ./storage/users:/storage/users
      environment:
        TZ: ${TZ}
      command:
        - -u
        - "${SAMBA_USER};${SAMBA_PASSWORD}"
        - -s
        - "Public;/storage/public;yes;no;yes;all;none"
        - -s
        - "Media;/storage/media;yes;no;yes;all;none"
        - -s
        - "Users;/storage/users;yes;no;no;${SAMBA_USER};${SAMBA_USER}"
      networks:
        storage_net:
          ipv4_address: 10.30.0.10

    # --- NEXTCLOUD DATABASE (Totalmente aislada) ---
    db_nextcloud:
      image: mariadb:10.11
      container_name: db_nextcloud
      restart: unless-stopped
      command: --transaction-isolation=READ-COMMITTED --log-bin-trust-function-creators=1
      volumes:
        - ./config/nextcloud_db:/var/lib/mysql
      environment:
        MYSQL_ROOT_PASSWORD: ${NEXTCLOUD_DB_PASSWORD}
        MYSQL_PASSWORD: ${NEXTCLOUD_DB_PASSWORD}
        MYSQL_DATABASE: nextcloud
        MYSQL_USER: nextcloud
      networks:
        nextcloud_db_net:    
          ipv4_address: 10.40.0.20

  networks:
    # Reverse proxy network
    edge_net:
      driver: bridge
      ipam:
        config:
          - subnet: 10.0.0.0/27      

    # DNS and Cloudflare network
    dns_cloudflare_net:
      driver: bridge
      ipam:
        config:
          - subnet: 10.10.0.0/27

    # Apps network
    apps_net:
      driver: bridge
      ipam:
        config:
          - subnet: 10.20.0.0/24

    # Storage network
    storage_net:
      driver: bridge
      ipam:
        config:
          - subnet: 10.30.0.0/28

    # Nexcloud_db network (Internal)
    nextcloud_db_net:
      driver: bridge
      internal: true                 
      ipam:
        config:
          - subnet: 10.40.0.0/27
